language: node_js
node_js: node

install:
  - npm install
  - npm install --save foglet-core
  - npm install --save-dev foglet-scripts

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

after_success:
  - npm start